apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc
  namespace: default
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-contenedor
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mi-volumen
      volumes:
      - name: mi-volumen
        persistentVolumeClaim:
          claimName: mi-pvc
